extends:
  - openlayers
  - plugin:@typescript-eslint/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  requireConfigFile: false
  ecmaVersion: 2020
  sourceType: module
plugins:
 - import
 - "@openlayers"
settings:
  import/parsers:
      "@typescript-eslint/parser":
        - .ts
        - .js
rules:
  jsdoc/require-returns: off
  jsdoc/require-returns-type: off
  jsdoc/require-param-type: off
  jsdoc/require-param-description: off
  import/named: off
  no-console: off
  no-multi-assign: off
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/no-explicit-any": off