export const printerIcon = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->
<svg
    xmlns:inkscape="http://www.inkscape.org/namespaces/inkscape"
    xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
    xmlns="http://www.w3.org/2000/svg"
    xmlns:cc="http://web.resource.org/cc/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:sodipodi="http://inkscape.sourceforge.net/DTD/sodipodi-0.dtd"
    xmlns:svg="http://www.w3.org/2000/svg"
    xmlns:ns1="http://sozi.baierouge.fr"
    xmlns:xlink="http://www.w3.org/1999/xlink"
    id="svg1468"
    sodipodi:docname="printer1.svg"
    viewBox="0 0 187.5 187.5"
    sodipodi:version="0.32"
    version="1.0"
    y="0"
    x="0"
    inkscape:version="0.42"
  >
  <sodipodi:namedview
      id="base"
      bordercolor="#666666"
      inkscape:pageshadow="2"
      inkscape:window-width="704"
      pagecolor="#ffffff"
      inkscape:zoom="1.8346667"
      inkscape:window-x="66"
      borderopacity="1.0"
      inkscape:current-layer="svg1468"
      inkscape:cx="93.750000"
      inkscape:cy="93.750000"
      inkscape:window-y="66"
      inkscape:window-height="510"
      inkscape:pageopacity="0.0"
  />
  <g
      id="layer1"
    >
    <g
        id="g2388"
        transform="translate(-527.55 -379)"
      >
      <rect
          id="rect2352"
          style="stroke-linejoin:round;stroke:#000000;stroke-linecap:round;stroke-width:3.1212;fill:#ffffff"
          rx="10"
          ry="10"
          height="58.321"
          width="145.8"
          y="448.86"
          x="547.3"
      />
      <rect
          id="rect2356"
          style="stroke-linejoin:round;stroke:#000000;stroke-linecap:round;stroke-width:3.1212;fill:#ffffff"
          height="39.464"
          width="87.326"
          y="498.72"
          x="576.54"
      />
      <path
          id="path2358"
          style="stroke:#000000;stroke-linecap:round;stroke-width:4.0576;fill:none"
          d="m561.88 468.75h115.32"
      />
      <rect
          id="rect2360"
          style="stroke-linejoin:round;stroke:#000000;stroke-linecap:round;stroke-width:3.1212;fill:#ffffff"
          height="44.549"
          width="87.482"
          y="404.06"
          x="576.46"
      />
      <path
          id="path2362"
          style="stroke:#000000;stroke-width:2.0808;fill:none"
          d="m587.07 527.07h66.27"
      />
      <path
          id="path2364"
          style="stroke:#000000;stroke-width:2.0808;fill:none"
          d="m587.07 520.44h66.27"
      />
      <path
          id="path2366"
          style="stroke:#000000;stroke-width:2.0808;fill:none"
          d="m587.07 513.81h66.27"
      />
      <path
          id="path2368"
          style="stroke:#000000;stroke-width:2.0808;fill:none"
          d="m587.07 507.19h66.27"
      />
    </g
    >
  </g
  >
  <metadata
    >
    <rdf:RDF
      >
      <cc:Work
        >
        <dc:format
          >image/svg+xml</dc:format
        >
        <dc:type
            rdf:resource="http://purl.org/dc/dcmitype/StillImage"
        />
        <cc:license
            rdf:resource="http://creativecommons.org/licenses/publicdomain/"
        />
        <dc:publisher
          >
          <cc:Agent
              rdf:about="http://openclipart.org/"
            >
            <dc:title
              >Openclipart</dc:title
            >
          </cc:Agent
          >
        </dc:publisher
        >
        <dc:title
          >Printer icon</dc:title
        >
        <dc:date
          >2006-12-26T00:00:00</dc:date
        >
        <dc:description
        />
        <dc:source
          >https://openclipart.org/detail/24825/-by--24825</dc:source
        >
        <dc:creator
          >
          <cc:Agent
            >
            <dc:title
              >Anonymous</dc:title
            >
          </cc:Agent
          >
        </dc:creator
        >
      </cc:Work
      >
      <cc:License
          rdf:about="http://creativecommons.org/licenses/publicdomain/"
        >
        <cc:permits
            rdf:resource="http://creativecommons.org/ns#Reproduction"
        />
        <cc:permits
            rdf:resource="http://creativecommons.org/ns#Distribution"
        />
        <cc:permits
            rdf:resource="http://creativecommons.org/ns#DerivativeWorks"
        />
      </cc:License
      >
    </rdf:RDF
    >
  </metadata
  >
</svg
>
`;
